name: ose-course-projects

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- python
- numpy
- pandas
- matplotlib
- sphinx
- pandoc
- flake8
- pytest
- pytest-black
- pytest-flake8
- scipy
- jupyterlab
- jupyter
- ipython
- pip
- nbsphinx
- nb_black
- pip:
  - seaborn
  - black-nb
  - flake8-nb
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
